name: retrain-mlflow-project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          auto-activate-base: true

      - name: Install MLflow (system)
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub

      - name: Set MLflow tracking env (Dagshub)
        shell: bash -l {0}
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USER }}/${{ secrets.DAGSHUB_REPO }}.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Debug (safe)
        shell: bash -l {0}
        run: |
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
          echo "MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME"
          conda --version

      - name: Run MLflow Project (Retrain)
        shell: bash -l {0}
        run: |
          mlflow run MLProject -P data_path=adult_preprocessing.csv -P target_col=income
